[package]
name = "silica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taffy = "0.3"
type-map = "0.5"
glyph_brush = "0.7"
